version: '3.5'
services:
  app:
    container_name: app
    image: asree001/app-ems
    ports:
      - "192.168.1.138:3000:3000"
    platform: 'linux/amd64'

#   caddy:
#     container_name: caddy
#     image: lucaslorentz/caddy-docker-proxy:alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - ./data:/data
#       - ./config:/config
#     depends_on:
#       - app

# networks:
#   caddy_network:
#     # สร้าง Docker network
#     driver: bridge
